/* Generated By:JavaCC: Do not edit this line. MyPascalTreeConstants.java Version 5.0 */
public interface MyPascalTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM_HEADER = 1;
  public int JJTVAR_GROUP = 2;
  public int JJTDEC_VAR = 3;
  public int JJTDECLARATION = 4;
  public int JJTARITHMETIC_OPERATION = 5;
  public int JJTRELATION_OPERATION = 6;
  public int JJTLOGIC_OPERATION = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTLOOP_FOR = 9;
  public int JJTIF_THEN_ELSE = 10;
  public int JJTFUNCTION_CALL = 11;
  public int JJTFUNCTION_CALL_PARAMS = 12;
  public int JJTFUNCTION_HEADER = 13;
  public int JJTFUNCTION = 14;
  public int JJTINSTRUCTION = 15;
  public int JJTHEADER = 16;
  public int JJTTOKEN_PROGRAM = 17;
  public int JJTTOKEN_IDENTIFIER = 18;
  public int JJTTOKEN_SEMICOLON = 19;
  public int JJTTOKEN_BEGIN = 20;
  public int JJTTOKEN_END_PERIOD = 21;
  public int JJTTOKEN_COMMA = 22;
  public int JJTTOKEN_COLON = 23;
  public int JJTTOKEN_TYPE = 24;
  public int JJTTOKEN_VAR = 25;
  public int JJTTOKEN_L_BRACKET = 26;
  public int JJTTOKEN_R_BRACKET = 27;
  public int JJTTOKEN_NUMBER = 28;
  public int JJTTOKEN_REAL_NUMBER = 29;
  public int JJTTOKEN_ARITHMETIC_OPERATOR = 30;
  public int JJTTOKEN_BOOL = 31;
  public int JJTTOKEN_RELATIONAL_OPERATOR = 32;
  public int JJTTOKEN_LOGIC_OPERATOR_NOT = 33;
  public int JJTTOKEN_LOGIC_OPERATOR = 34;
  public int JJTTOKEN_STRING = 35;
  public int JJTTOKEN_ASSIGNMENT = 36;
  public int JJTTOKEN_FOR = 37;
  public int JJTTOKEN_TO = 38;
  public int JJTTOKEN_DO = 39;
  public int JJTTOKEN_END_SEMICOLON = 40;
  public int JJTTOKEN_ELSE = 41;
  public int JJTTOKEN_IF = 42;
  public int JJTTOKEN_THEN = 43;
  public int JJTTOKEN_END = 44;
  public int JJTTOKEN_FUNCTION = 45;


  public String[] jjtNodeName = {
    "INICIO",
    "CABECALHO DO PROGRAMA",
    "GRUPO DE VARIAVEIS",
    "DECLARACOES DE VARIAVEIS",
    "DECLARACAO",
    "OPERADORES ARITMETICOS",
    "OPERADORES RELACIONAIS",
    "OPERADORES LÓGICOS",
    "ATRIBUICAO",
    "LOOP TIPO FOR",
    "IF THEN ELSE",
    "CHAMADA DE FUNCAO",
    "CHAMADA DE FUNCAO PARAMETROS",
    "CABECALHO DE FUNCAO",
    "FUNCTION",
    "INSTRUCTION",
    "CABECALHO",
    "TOKEN PROGRAMA",
    "TOKEN IDENTIFICADOR",
    "TOKEN PONTOEVIRGULA",
    "TOKEN BEGIN",
    "TOKEN END PONTO",
    "TOKEN VIRGULA",
    "TOKEN DOIS PONTOS",
    "TOKEN TIPO",
    "TOKEN VARIAVEL",
    "TOKEN_L_BRACKET",
    "TOKEN_R_BRACKET",
    "TOKEN NUMERO",
    "TOKEN NUMERO REAL ",
    "TOKEN OPERADOR ARITMETICO",
    "TOKEN BOOL",
    "TOKEN OPERADOR RELACIONAL",
    "TOKEN OPERADOR RELACIONAL NOT",
    "TOKEN OPERADOR LOGICO",
    "TOKEN STRING",
    "TOKEN ATRIBUICAO",
    "TOKEN FOR",
    "TOKEN TO",
    "TOKEN DO",
    "TOKEN END PONTOEVIRGULA",
    "TOKEN ELSE",
    "TOKEN IF",
    "TOKEN THEN",
    "TOKEN END",
    "TOKEN FUNCTION",
  };
}
/* JavaCC - OriginalChecksum=95f121235d5e940726f363cd1250ec62 (do not edit this line) */
